- docker-compose.yml
- docker/nginx.conf
- `nginx.conf`
- backendのポートが誤っていたのでそこの修正
- `location`内の`proxy_pass`の末尾`/`が抜けていたので修正
- `docker-compose.yml`
- `MARIADB_HOSTNAME`に指定されているコンテナ名が誤っていたので修正
> Dockerの一部修正

- .github/workflows/go.yml
#11 
- ~~swagger (spectral)~~
- 現状の`swagger.yml`だとLintで次のエラーを吐く
- `/paths//applications/get/parameters/0 should have required property '$ref'`
- https://github.com/stoplightio/spectral/issues/403
- server
- ~~client~~ あとで
> Github Actionsの設定

- model/applications_detail.go
- `putApplicationsDetail`にて`Find`してきた`detail`の`UpdateAt`がそのまま使われていたので、ゼロ値で初期化してDBテーブルに追加した時点での時刻が挿入されるようにした
- `time.Now()`を入れた方が明確かもしれない？
close #91
> detail_logsのUpdateAtが更新されるようにした

- router/auth.go
- router/service.go
https://stackoverflow.com/questions/21865681/sessions-variables-in-golang-not-saved-while-using-gorilla-sessions の
> Your sessions aren't "sticking" is that you're setting the Path as /loginSession - so when a user visits any other path (i.e. /), the session isn't valid for that scope.
だと思ったのでsessionが全部のパスで有効になるかなと思って全部に追加しました。できるかはわからず......
> sess.Optionsを全てのsessに追加

- .dockerignore
- Dockerfile
- client/.dockerignore
- client/Dockerfile
- development/Dockerfile
- docker-compose.yml
- docker/staging/docker-compose.yml
staging、developmentのdocker関連諸々を調整した。
- 無駄にopenssl、curlを入れているところの排除
- ca-certificateのupdateをしていなかったのでupdateするようにする
- dockerignoreがcontext以外のディレクトリに置かれていて効いていなかったのでcontextに置くように
- go-taskを毎回gitで取ってきてビルドしていたのをバイナリのダウンロードでインストールするように
- つなぐ必要性のないコマンドを切って可読性を向上
- developmentでは起動時にボリュームのマウントとgoのbuildが行われるのでdevelopmentのDockerfileからこの部分を排除
- mysqlのタイムゾーンが設定されていなかったので設定
チューニング前
チューニング後
> dockerチューニング

- .github/workflows/go.yml
- Dockerfile
- development/Dockerfile
https://github.com/golang/go/issues/36524 の修正がほしい
Goしかあげてないからmariadbとかもあげたほうがいいのかも
> Goを1.17.5にアップデート:genbacat:

- docs/swagger.yaml
- temmさんに確認したところ、タグのdescriptionがいらないという話だったのでdescriptionを消し、それに伴いタグ情報のPUTも消しました。気軽につけたり消したりできるtraQのタグみたいな使い方になると思います。
- status変更のreasonはcommentにするという話があったので修正しました。
- リクエストのPOSTとPUTでtagの配列の中身はIDだけでいいと思うので修正しました。
> swaggerを修正

- .air.toml
https://github.com/traPtitech/portal/pull/150/commits/aa7c1412c9abefd68481b362fbc788a62a316e3e
と同じ
> go buildのオプションに-buildvcs=falseを追加

- main.go
- router/auth.go
- router/group.go
- router/middleware.go
- router/request.go
こんな感じ
```text
jomon-server_1  | 2022-04-18T22:40:59.235+0900  ERROR   router/middleware.go:42 server error    {"requestMethod": "GET", "status": 500, "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36", "remoteIp": "172.23.0.1", "referer": "", "protocol": "HTTP/1.1", "requestUrl": "/api/auth/callback?code=G0iaX7R4we4sll95FUmlMQ2dpRMMUaNxIOT4", "requestSize": "", "responseSize": "3", "latency": "0.142614263s", "error": "code=500, message=ent: user not found"}
jomon-server_1  | github.com/traPtitech/Jomon/router.Handlers.AccessLoggingMiddleware.func1.1
jomon-server_1  |       /src/router/middleware.go:42
jomon-server_1  | github.com/labstack/echo/v4.(*Echo).ServeHTTP
jomon-server_1  | …
```
> loggingでerror等が正しく表示されるように修正

- docs/swagger.yaml
> :pencil: Rename `File` in `swagger.yaml`

- router/admin.go
- router/auth.go
- router/file.go
- router/group.go
- router/middleware.go
- router/request.go
- router/tag.go
- router/transaction.go
- router/user.go
> :white_check_mark: add logging codes

- docs/swagger.yaml
- model/transaction.go
- model/transaction_impl.go
- router/transaction.go
- router/transaction_test.go
> Transactions query

- model/transaction_impl_test.go
> :white_check_mark: Remove `t.Parallel` in transaction_impl_test

- .github/workflows/go.yml
- service/webhook.go
- testutil/random/ramdom.go
> golangci-lintまわりの修正

- .github/workflows/codeql.yml
> :wrench: Configure CodeQL explicitly

- ent/migrate/schema.go
- ent/mutation.go
- ent/runtime.go
- ent/schema/transactiondetail.go
- ent/transactiondetail.go
- ent/transactiondetail/transactiondetail.go
- ent/transactiondetail/where.go
- ent/transactiondetail_create.go
- ent/transactiondetail_query.go
- ent/transactiondetail_update.go
- model/mock_model/mock_transaction.go
- model/transaction.go
- model/transaction_detail.go
- model/transaction_detail_impl.go
- model/transaction_detail_impl_test.go
- model/transaction_impl.go
- model/transaction_impl_test.go
- router/transaction.go
- router/transaction_test.go
> transactionにtitleを追加

- docs/swagger.yaml
- model/request.go
- model/request_impl.go
- model/request_impl_test.go
- router/request.go
- router/request_test.go
> `GET /requests?created_by`

- go.mod
- model/admin_impl_test.go
- model/comment_impl_test.go
- model/file_impl_test.go
- model/group_impl_test.go
- model/request_impl.go
- model/request_impl_test.go
- model/request_status_impl_test.go
- model/request_target_impl_test.go
- model/tag_impl_test.go
- model/transaction_detail_impl_test.go
- model/transaction_impl_test.go
- model/user_impl_test.go
- router/admin_test.go
- router/file_test.go
- router/group_test.go
- router/request_test.go
- router/tag_test.go
- router/transaction_test.go
- router/user_test.go
- testutil/cmp.go
> :white_check_mark: Testでgo-cmpを使うように

- model/admin_impl_test.go
- model/comment_impl_test.go
- model/file_impl_test.go
- model/group_impl_test.go
- model/request_impl_test.go
- model/request_status_impl_test.go
- model/request_target_impl_test.go
- model/tag_impl_test.go
- model/transaction_detail_impl_test.go
- model/transaction_impl_test.go
- model/user_impl_test.go
- router/admin_test.go
- router/auth_test.go
- router/file_test.go
- router/group_test.go
- router/request_test.go
- router/tag_test.go
- router/transaction_test.go
- router/user_test.go
#821
ひとまず`router/admin_test.go`の中身のみ変更
基本`assert`を`require`に変更していったがHTTPステータスと`resBody`の比較する部分はエラー時に両方見れた方がいいと思ったので`assert`のままにした
`resuire`に変更する中で不要な`if`文を消した
> `assert` vs `require`

- router/file.go
- router/file_test.go
- storage/local.go
- storage/mock_storage/mock_storage.go
- storage/s3.go
- storage/storage.go
- storage/swift.go
#907
`Storage`interfaceに`context.Context`を追加
`./storage`のmock更新
`Swift`と`Local`に[おまじない](https://zenn.dev/seri_k/articles/df3052543f1c62)追加
> add contect.Context to Storage interface method argument
