traPtitech/Jomon

.gitignore
development/Dockerfile
docker-compose.yml
runner.conf

- Go側がdbのイニシャライズを待たずに走って`connection refused`でコケる問題の修正
- GoのHot Reload

Introduce dockerize and fresh

---

.github/workflows/go.yml
model/db.go
model/db_test.go

Github Actionsでデータベースを扱う

---

docs/swagger.yaml

applicationIdがintになっているがschema.mdの記述がuuidになっていることと矛盾している｡

Fix swagger.yaml

---

docker/nginx.conf
mock-for-client.yml

fix mock_for_client

---

model/application_test.go
model/comment.go
model/comment_test.go
model/db_test.go
model/repay_user.go
router/comments.go
router/comments_test.go
router/router.go

CommentのAPIを実装

---

router/router.go
router/states.go

Statesの誤字を修正

---

docs/swagger.yaml
model/administrator_test.go
model/db_test.go
model/user.go
model/user_test.go
router/applications.go
router/applications_test.go
router/comments.go
router/comments_test.go
router/router.go
router/users.go
router/users_test.go

- User関連のAPIを実装
- APIアクセス時にtraQのGET /users/meで認証
- Userのrouterのテストを実装
- Administratorのテストを実装
Userのmodelのテストについては、~~traQのAPIに用いるtokenを取る必要があり、上手くやる方法が思いつかなかったので実装していません~~実装しました

User周りのAPIを実装

---

client/src/store/applicationDetail.js

詳細画面のログを並び替え

---

client/src/views/components/Application.vue

StateChipを共通化した

---

docs/schema.md
model/application.go
model/application_test.go
model/applications_detail.go
model/applications_detail_test.go
model/applications_image.go
model/comment.go
model/repay_user.go
model/states_log.go

- paid_at、repaid_atのみdate
- それ以外の時刻はdatetime
- schema.mdも合わせて修正

timestampの代わりにdatetime、dateを使用

---

docs/schema.md
model/repay_user.go
router/applications_test.go

repaid_by_user_trap_idをnot nullとして統一

---

docker-compose.yml

クライアントの開発環境でホットリロード

---

docker/nginx.conf
main.go
router/service.go
router/service_debug.go

- ロガーの追加
- `nginx.conf`の`client_max_body_size`の設定
- デバッグビルド時に`User`の`is_admin`が付与されないバグの修正

デバッグ用のサーバサイドの修正

---

router/auth.go

コールバックのレスポンスを変更

---

client/src/views/NewApplicationPage.vue

指摘された部分を修正しました

---

client/src/views/NewApplicationPage.vue

paid_atを修正

---

.gitignore
model/applications_image.go

ApplicationImageのJSONの修正

---

model/application.go

以前まではコメントが0であるときはそもそもエントリがなかったので, 空配列を持つように変更
Closes #79

DetailedApplicationがcommentsエントリを必ず持つように

---

client/src/views/components/StateButtonController.vue

承認の方のURLも修正

---

model/repay_user.go

一人にRepayすると全員Repayされるバグの修正

---

docs/schema.md
docs/swagger.yaml

また`/applications/{applicationId}/states/repaid/{repaidToId}`がリクエストボディに`repaid_at`を要求するようにした｡

RepaidUserにcreated_atを追加

---

go.mod
go.sum
model/auth.go
router/auth.go
router/service.go

- 依存ライブラリの更新
- 有効期限の修正(1000d -> 7d)

OAuth周りの修正

---

model/user.go

Usersのフィルタ

---

model/application.go
model/repay_user.go
model/repay_user_test.go
router/applications_test.go
router/states.go
router/states_test.go

#99 の実装
RepaidAtをbodyから取るように変更
CreatedAtの実装
伴うtestの変更

swagger、DBスキーマにあわせた変更

---

.github/workflows/image.yml
README.md
client/src/views/NewApplicationPage.vue
client/src/views/components/FixApplicationDetail.vue

GitHub actions

---

model/db.go
model/db_test.go

EstablishConnection()の最後でtrueにするようにしました。よろしくお願いします。
Closes #117

BlockGlobalUpdateをtrueに

---

router/states_test.go

adminならこれこれ、作成者ならこれこれみたいな条件のテストを一応追加しておきました。よろしくお願いします。

Statusに関するTestの追加

---

model/application.go
model/application_test.go

年度の絞り込みを実装

---

router/applications.go
router/applications_test.go

負の金額でBadRequestを吐くように変更

---

client/src/utils/api.js
model/user.go
router/auth.go
router/service.go

close #108
URL/oauth2/*のGETはレスポンスに変更がなかったのでURLを変えるだけ、URL/users/*はsuspendedはデフォルトで返さないようになったらしいのでそこだけ変更しました。
よろしくお願いします。

traQAPIv3への対応

---

router/applications.go

#133 
これでサーバー側は直ると思います。よろしくお願いします。

adminかつSubmittedでもFixRequiredでもないとき通さないように修正

---

client/src/views/components/StateButtonController.vue

状態変更ボタンの適切な非表示を実装

---

model/administrator.go
model/administrator_test.go

```text
(/src/model/administrator.go:47)
jomon-server_1  | [2020-09-07 13:48:11]  Error 1062: Duplicate entry 'MyUser' for key 'PRIMARY' 
jomon-server_1  |
jomon-server_1  | (/src/model/administrator.go:47)
jomon-server_1  | [2020-09-07 13:48:11]  Error 1062: Duplicate entry 'AdminUser' for key 'PRIMARY'
```
これを修正
すでにkeyがある場合は追加しない(Updateのみする)、`FirstOrCreate()`を採用

Change AddAdministrator(Create to FirstOrCreate)

---

router/applications.go

日付の処理がうまくできていませんでした(RFC3339はUTCなので、UTCとJSTで比べていた)
UTCの日付を一度`2006-01-02`の形に変換し、それを再度東京の時間でtime.Timeに変換することでちゃんと処理できるようにしました。
close #235

fix Patch Application

---

model/webhook.go
router/router.go
router/service.go

- マージする
- WebHookを作る
- .envにWebHookの情報を載せる
で指定したチャンネルに申請書が作成された通知はいくはず(多分...)
それ以外の通知は後日
close #214

add webhook

---

model/applications_detail.go
model/webhook.go
router/router.go
router/service_debug.go

- Skipperを用いるように変更
- PaidAtの部分がUnmarshalできていなかったのでUnmarshalを記述

fix webhook and add webhook to service_debug.go

---

model/webhook.go

Webhookのレスポンスが`Application`ではなかったので、新しくstructを作って修正
close #275

Webhookの修正

---

docker-compose.yml

Colorize logs

---

.github/dependabot.yml

Dependabotを修正

---

docker-compose.yml

phpmyadminを導入

---

.github/workflows/go.yml

GitHub ActionsのGoのTest時の環境変数を修正

---

README.md

README.mdの英語の綴りを修正

---

ent/runtime.go
ent/schema/tag.go
ent/tag/tag.go
ent/tag_create.go
ent/tag_update.go
go.sum
model/model.go
model/model_test.go
model/repository_test.go
model/tag_impl.go
model/tag_impl_test.go

tagのテストを追加、テスト周りの機構の修正

---

model/repository_test.go

t.Helper()を追加

---

Makefile
README.md

Makefileでテストできるように修正

---

docs/swagger.yaml
model/applications_image.go

これが原因
extを強気の全探索
https://github.com/golang/go/issues/39283
あとなんかエラー出たからswaggerのTYPOもなおした
マージされたらデプロイもお願いしたい

画像が読み込まれないバグを修正

---

docs/schema.md
docs/swagger.yaml
model/application_test.go
model/applications_detail_test.go

ドキュメントを変更しちゃってたからopenapi使ってるテストが落ちてた
time.Timeの比較が沼でテスト落ちてたので修正

docsを戻して、テストを修正

---

router/states.go
router/states_test.go

adminでも作成者でもない人がapiを叩くことで状態を自由に変更できてしまう脆弱性の修正

状態遷移の脆弱性修正

---

model/request_impl_test.go

2021年度が終わってテストFailするようになったので(ちゃんとnilにしてください)

GetRequestsのテストを修正

---

docs/swagger.yaml
router/request.go
router/router.go

put/delete commentのapiを削除

---

docs/swagger.yaml

fully_repaid->compeleted(サーバーに合わせた)

swaggerの状態を修正

---

docs/swagger.yaml

タイトルのsortがtransactionに含まれていたのを修正

docs: sortQueryを修正

---

Makefile

Makefileで`uploads`フォルダを削除しないように修正

---

.github/workflows/go.yml

update go version on go.yml

---

docs/swagger.yaml
model/request_impl.go
model/request_impl_test.go

RequestにAmountのsortを追加

---

README.md

READMEに必要な環境変数を列挙

---

router/auth.go

loginしたときにユーザーがJomonにいなかったら作るように修正

---

router/request.go
router/request_test.go

GetRequestsでnullを返さないように

---

docs/swagger.yaml
service/webhook.go

WebhookのAmountの部分を修正 & swaggerのtargetにuuid指定がついていなかったので修正

---

service/webhook.go

Webhookの投稿内容を修正

---

router/auth.go

- `gob.Register`を追加
- わかりやすいエラーを出すように修正

authのエラーを修正

---

model/request.go
model/request_impl.go
model/request_status.go
model/request_status_impl.go
router/request.go
router/request_test.go

Requestのレスポンスを修正

---

router/transaction.go

transactionのgroupがnilの場合を修正

---

.github/workflows/image-v1.yml
.github/workflows/image-v2.yml

https://github.com/traPtitech/Jomon/actions/runs/9028333861/job/24808628505
落ちたので

:adhesive_bandage: イメージ作成のアクションにpermission設定

---

.github/dependabot.yml

:wrench: Dependabot再設定

---

Dockerfile
Dockerfile.dev
go.mod
testutil/random/ramdom.go

- バージョンを変更してdockerfile.devの起動を確認しました
- `for i := 0; i < n; i++`から`for i := range n`に置き換えました

goのバージョンを1.22.3に変更

---

.github/workflows/go.yml

:wrench: Use codecov/codecov-action@v4

---

Dockerfile.dev
Makefile
compose.yml

Fix docker

---

router/request.go

:recycle: Reduce `return true`

---

router/admin_test.go
router/file_test.go
router/group_test.go
router/request_test.go
router/tag_test.go
router/transaction_test.go
router/user_test.go
testutil/context.go

:white_check_mark: httptest使う

---

logging/context.go
logging/load.go
main.go
model/admin_impl_test.go
model/comment_impl_test.go
model/file_impl_test.go
model/group_impl_test.go
model/request_impl_test.go
model/request_status_impl_test.go
model/request_target_impl_test.go
model/tag_impl_test.go
model/transaction_detail_impl_test.go
model/transaction_impl_test.go
model/user_impl_test.go
router/admin.go
router/auth.go
router/file.go
router/group.go
router/middleware.go
router/request.go
router/router.go
router/router_test.go
router/tag.go
router/transaction.go
router/user.go
testutil/context.go
testutil/logger.go

:sparkles: `logging`パッケージ作った

---

.github/workflows/go.yml
.golangci.yml
router/request.go

v2が出てたらしい
https://golangci-lint.run/product/migration-guide/

Migrate golangci lint

---

docs/swagger.yaml

:pencil: Update swagger.yaml

---

main.go
router/router.go
service/webhook.go

`WebhookService`

---

logging/load.go

`zap.Logger`の設定

---

model/request_impl.go
router/request.go
router/request_test.go

`RequestResponse`と`RequestDetailResponse`に分けた

---

model/request_impl_test.go
model/request_target_impl_test.go

`time.Now`のタイミングをいじった

---

router/request.go
router/request_test.go
router/tag.go
router/tag_test.go
router/transaction.go
router/transaction_test.go

tag.goの構造体名を変更

---

router/auth.go
router/wrapsession/wrapper.go

change redirect url in AuthCallback

---

router/tag.go
router/tag_test.go

router.TagにあるDescriptionを削除
